version: '2'

volumes:
  nextcloud:
  db:

services:

  db:
    image: mariadb:10.5
    restart: always
    hostname: db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USER}

  app1:
    image: nextcloud
    restart: always
    hostname: app1
    expose:
      - 80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USER}
      - MYSQL_HOST=db

  app2:
    image: nextcloud
    restart: always
    hostname: app2
    expose:
      - 80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USER}
      - MYSQL_HOST=db

  haproxy:
    build: haproxy
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2